"""add_oauth_fields

Revision ID: 0fdf067e89d0
Revises: ce6573f9b439
Create Date: 2026-01-25 01:00:42.869230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0fdf067e89d0'
down_revision: Union[str, Sequence[str], None] = 'ce6573f9b439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oauth_provider', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
        batch_op.add_column(sa.Column('oauth_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('oauth_id')
        batch_op.drop_column('oauth_provider')

    # ### end Alembic commands ###
