"""add interface fields

Revision ID: add_interface_fields
Revises:
Create Date: 2026-02-11 16:00:00

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy.engine import Connection
from sqlmodel import SQLModel, Column, Integer, JSON

# revision
revision = 'add_interface_fields'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interface', 'order', Integer, nullable=True, server_default='0')
    op.add_column('interface', 'auth_config', JSON, nullable=True, server_default='{}')


def downgrade(schema: str) -> None:
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interface', 'order')
    op.drop_column('interface', 'auth_config')
