"""initial_schema

Revision ID: 1cf362f7d6d9
Revises: 
Create Date: 2026-03-04 22:04:28.036245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1cf362f7d6d9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=100), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=True),
    sa.Column('session_type', sa.String(length=50), nullable=False),
    sa.Column('ai_model_used', sa.String(length=100), nullable=True),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_conversations_conversation_id'), ['conversation_id'], unique=True)

    op.create_table('ai_provider_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_name', sa.String(length=255), nullable=False),
    sa.Column('provider_type', sa.String(length=100), nullable=False),
    sa.Column('api_key_encrypted', sa.String(length=500), nullable=False),
    sa.Column('api_endpoint', sa.String(length=500), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_provider_configs', schema=None) as batch_op:
        batch_op.create_index('idx_ai_provider_enabled_default', ['is_enabled', 'is_default'], unique=False)
        batch_op.create_index('idx_ai_provider_user_type', ['user_id', 'provider_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_provider_configs_provider_name'), ['provider_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_provider_configs_provider_type'), ['provider_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_provider_configs_user_id'), ['user_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file_attachments', schema=None) as batch_op:
        batch_op.create_index('idx_file_attachments_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_attachments_file_id'), ['file_id'], unique=True)

    op.create_table('global_params',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('class_name', sa.String(length=255), nullable=False),
    sa.Column('method_name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('input_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_name', 'method_name', name='uq_global_params_class_method')
    )
    with op.batch_alter_table('global_params', schema=None) as batch_op:
        batch_op.create_index('idx_global_params_class_name', ['class_name'], unique=False)

    op.create_table('globalconfig',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=1000), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('globalconfig', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_globalconfig_key'), ['key'], unique=True)

    op.create_table('notificationchannel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('channel_type', sa.String(length=50), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resource', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requirements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requirement_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('module_id', sa.String(length=100), nullable=True),
    sa.Column('module_name', sa.String(length=255), nullable=False),
    sa.Column('iteration', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('attachments', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_conversation_id', sa.String(length=100), nullable=True),
    sa.Column('clarification_status', sa.String(length=20), nullable=False),
    sa.Column('risk_points', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('test_case_suite_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirements_requirement_id'), ['requirement_id'], unique=True)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('test_case_knowledge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('module_name', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('case_type', sa.String(length=50), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_case_knowledge', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_case_knowledge_test_case_id'), ['test_case_id'], unique=True)

    op.create_table('test_case_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('template_structure', sa.JSON(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_case_templates', schema=None) as batch_op:
        batch_op.create_index('idx_test_case_templates_category', ['category'], unique=False)

    op.create_table('test_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(length=50), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('test_suite_id', sa.Integer(), nullable=True),
    sa.Column('test_point_id', sa.Integer(), nullable=True),
    sa.Column('module_name', sa.String(length=100), nullable=False),
    sa.Column('page_name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('case_type', sa.String(length=50), nullable=False),
    sa.Column('preconditions', sa.JSON(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('is_automated', sa.Boolean(), nullable=False),
    sa.Column('complexity', sa.String(length=20), nullable=True),
    sa.Column('estimated_time', sa.Integer(), nullable=False),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=False),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.create_index('idx_functional_tc_req_module', ['requirement_id', 'module_name', 'page_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_cases_case_id'), ['case_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_test_cases_requirement_id'), ['requirement_id'], unique=False)

    op.create_table('test_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('sub_category', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_points', schema=None) as batch_op:
        batch_op.create_index('idx_test_points_req_cat_pri', ['requirement_id', 'category', 'priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_points_requirement_id'), ['requirement_id'], unique=False)

    op.create_table('userrole',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('oauth_provider', sa.String(length=50), nullable=True),
    sa.Column('oauth_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_oauth', ['oauth_provider', 'oauth_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('owner', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index('idx_projects_created_by_name', ['created_by', 'name'], unique=True)
        batch_op.create_index(batch_op.f('ix_projects_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_key'), ['key'], unique=True)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE')
    )
    op.create_table('document',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interface_folders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['interface_folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interface_folders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interface_folders_project_id'), ['project_id'], unique=False)

    op.create_table('keywords',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('class_name', sa.String(length=100), nullable=False),
    sa.Column('method_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('parameters', sa.Text(), nullable=True),
    sa.Column('return_type', sa.String(length=100), nullable=True),
    sa.Column('is_built_in', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.create_index('idx_keywords_class_method', ['class_name', 'method_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_keywords_is_built_in'), ['is_built_in'], unique=False)
        batch_op.create_index(batch_op.f('ix_keywords_is_enabled'), ['is_enabled'], unique=False)

    op.create_table('project_data_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('db_type', sa.String(length=50), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('db_name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('variable_name', sa.String(length=100), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_test_at', sa.DateTime(), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_data_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_data_sources_project_id'), ['project_id'], unique=False)

    op.create_table('project_environments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('domain', sa.String(length=500), nullable=False),
    sa.Column('variables', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('headers', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('is_preupload', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_environments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_environments_project_id'), ['project_id'], unique=False)

    op.create_table('scenarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('pre_sql', sa.Text(), nullable=True),
    sa.Column('post_sql', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenarios_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenarios_project_id'), ['project_id'], unique=False)

    op.create_table('test_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cron_expression', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('next_run', sa.DateTime(), nullable=True),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_plans_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_plans_status'), ['status'], unique=False)

    op.create_table('api_test_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('yaml_content', sa.Text(), nullable=False),
    sa.Column('config_data', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['project_environments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_test_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_test_cases_environment_id'), ['environment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_test_cases_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_test_cases_project_id'), ['project_id'], unique=False)

    op.create_table('datasets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('scenario_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('csv_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datasets_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasets_scenario_id'), ['scenario_id'], unique=False)

    op.create_table('documentversion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('change_note', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interfaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('folder_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('headers', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('params', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('body', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('body_type', sa.String(length=50), nullable=False),
    sa.Column('cookies', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('auth_config', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('schema_snapshot', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['interface_folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interfaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interfaces_project_id'), ['project_id'], unique=False)

    op.create_table('plan_scenarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_plan_id', sa.String(length=36), nullable=False),
    sa.Column('scenario_id', sa.String(length=36), nullable=False),
    sa.Column('execution_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_plan_id'], ['test_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan_scenarios', schema=None) as batch_op:
        batch_op.create_index('idx_plan_scenarios_plan_order', ['test_plan_id', 'execution_order'], unique=True)
        batch_op.create_index(batch_op.f('ix_plan_scenarios_scenario_id'), ['scenario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_scenarios_test_plan_id'), ['test_plan_id'], unique=False)

    op.create_table('scenario_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scenario_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keyword_type', sa.String(length=50), nullable=False),
    sa.Column('keyword_name', sa.String(length=255), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenario_steps', schema=None) as batch_op:
        batch_op.create_index('idx_scenario_steps_scenario_id', ['scenario_id'], unique=False)
        batch_op.create_index('idx_scenario_steps_sort_order', ['sort_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenario_steps_scenario_id'), ['scenario_id'], unique=False)

    op.create_table('test_executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_case_id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('result_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['project_environments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_executions_environment_id'), ['environment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_executions_test_case_id'), ['test_case_id'], unique=False)

    op.create_table('test_plan_executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_plan_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_scenarios', sa.Integer(), nullable=False),
    sa.Column('passed_scenarios', sa.Integer(), nullable=False),
    sa.Column('failed_scenarios', sa.Integer(), nullable=False),
    sa.Column('skipped_scenarios', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['test_plan_id'], ['test_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_plan_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_plan_executions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_plan_executions_test_plan_id'), ['test_plan_id'], unique=False)

    op.create_table('testreport',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('success', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('duration', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_test_executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_case_id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('result_data', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('passed_steps', sa.Integer(), nullable=False),
    sa.Column('failed_steps', sa.Integer(), nullable=False),
    sa.Column('skipped_steps', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('error_category', sa.String(length=50), nullable=True),
    sa.Column('execution_options', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['project_environments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['test_case_id'], ['api_test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_test_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_test_executions_environment_id'), ['environment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_test_executions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_test_executions_test_case_id'), ['test_case_id'], unique=False)

    op.create_table('api_test_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_case_id', sa.String(length=36), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=50), nullable=False),
    sa.Column('step_config', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['api_test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_test_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_test_steps_step_order'), ['step_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_test_steps_step_type'), ['step_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_test_steps_test_case_id'), ['test_case_id'], unique=False)

    op.create_table('plan_execution_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_plan_execution_id', sa.String(length=36), nullable=False),
    sa.Column('scenario_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['test_plan_execution_id'], ['test_plan_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan_execution_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_execution_steps_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_execution_steps_test_plan_execution_id'), ['test_plan_execution_id'], unique=False)

    op.create_table('testcase',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('interface_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('pre_conditions', sa.String(length=1000), nullable=True),
    sa.Column('steps_data', sa.JSON(), nullable=False),
    sa.Column('engine_type', sa.String(length=50), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['interface_id'], ['interfaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testreportdetail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=100), nullable=False),
    sa.Column('node_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('request_data', sa.JSON(), nullable=True),
    sa.Column('response_data', sa.JSON(), nullable=True),
    sa.Column('error_msg', sa.String(length=1000), nullable=True),
    sa.Column('elapsed', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['testreport.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_test_step_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('step_name', sa.String(length=255), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('performance_metrics', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('response_data', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('validations', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('extracted_vars', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('error_info', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['api_test_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_test_step_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_test_step_results_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_test_step_results_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_test_step_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_test_step_results_status'))
        batch_op.drop_index(batch_op.f('ix_api_test_step_results_execution_id'))

    op.drop_table('api_test_step_results')
    op.drop_table('testreportdetail')
    op.drop_table('testcase')
    with op.batch_alter_table('plan_execution_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_execution_steps_test_plan_execution_id'))
        batch_op.drop_index(batch_op.f('ix_plan_execution_steps_status'))

    op.drop_table('plan_execution_steps')
    with op.batch_alter_table('api_test_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_test_steps_test_case_id'))
        batch_op.drop_index(batch_op.f('ix_api_test_steps_step_type'))
        batch_op.drop_index(batch_op.f('ix_api_test_steps_step_order'))

    op.drop_table('api_test_steps')
    with op.batch_alter_table('api_test_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_test_executions_test_case_id'))
        batch_op.drop_index(batch_op.f('ix_api_test_executions_status'))
        batch_op.drop_index(batch_op.f('ix_api_test_executions_environment_id'))

    op.drop_table('api_test_executions')
    op.drop_table('testreport')
    with op.batch_alter_table('test_plan_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_plan_executions_test_plan_id'))
        batch_op.drop_index(batch_op.f('ix_test_plan_executions_status'))

    op.drop_table('test_plan_executions')
    with op.batch_alter_table('test_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_executions_test_case_id'))
        batch_op.drop_index(batch_op.f('ix_test_executions_environment_id'))

    op.drop_table('test_executions')
    with op.batch_alter_table('scenario_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenario_steps_scenario_id'))
        batch_op.drop_index('idx_scenario_steps_sort_order')
        batch_op.drop_index('idx_scenario_steps_scenario_id')

    op.drop_table('scenario_steps')
    with op.batch_alter_table('plan_scenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_scenarios_test_plan_id'))
        batch_op.drop_index(batch_op.f('ix_plan_scenarios_scenario_id'))
        batch_op.drop_index('idx_plan_scenarios_plan_order')

    op.drop_table('plan_scenarios')
    with op.batch_alter_table('interfaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interfaces_project_id'))

    op.drop_table('interfaces')
    op.drop_table('documentversion')
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datasets_scenario_id'))
        batch_op.drop_index(batch_op.f('ix_datasets_project_id'))

    op.drop_table('datasets')
    with op.batch_alter_table('api_test_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_test_cases_project_id'))
        batch_op.drop_index(batch_op.f('ix_api_test_cases_name'))
        batch_op.drop_index(batch_op.f('ix_api_test_cases_environment_id'))

    op.drop_table('api_test_cases')
    with op.batch_alter_table('test_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_plans_status'))
        batch_op.drop_index(batch_op.f('ix_test_plans_project_id'))

    op.drop_table('test_plans')
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenarios_project_id'))
        batch_op.drop_index(batch_op.f('ix_scenarios_created_by'))

    op.drop_table('scenarios')
    with op.batch_alter_table('project_environments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_environments_project_id'))

    op.drop_table('project_environments')
    with op.batch_alter_table('project_data_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_data_sources_project_id'))

    op.drop_table('project_data_sources')
    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_keywords_is_enabled'))
        batch_op.drop_index(batch_op.f('ix_keywords_is_built_in'))
        batch_op.drop_index('idx_keywords_class_method')

    op.drop_table('keywords')
    with op.batch_alter_table('interface_folders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interface_folders_project_id'))

    op.drop_table('interface_folders')
    op.drop_table('document')
    op.drop_table('role_permissions')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_key'))
        batch_op.drop_index(batch_op.f('ix_projects_created_by'))
        batch_op.drop_index('idx_projects_created_by_name')

    op.drop_table('projects')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index('idx_users_oauth')

    op.drop_table('users')
    op.drop_table('userrole')
    with op.batch_alter_table('test_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_points_requirement_id'))
        batch_op.drop_index('idx_test_points_req_cat_pri')

    op.drop_table('test_points')
    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_cases_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_test_cases_case_id'))
        batch_op.drop_index('idx_functional_tc_req_module')

    op.drop_table('test_cases')
    with op.batch_alter_table('test_case_templates', schema=None) as batch_op:
        batch_op.drop_index('idx_test_case_templates_category')

    op.drop_table('test_case_templates')
    with op.batch_alter_table('test_case_knowledge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_case_knowledge_test_case_id'))

    op.drop_table('test_case_knowledge')
    op.drop_table('roles')
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirements_requirement_id'))

    op.drop_table('requirements')
    op.drop_table('permissions')
    op.drop_table('notificationchannel')
    with op.batch_alter_table('globalconfig', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_globalconfig_key'))

    op.drop_table('globalconfig')
    with op.batch_alter_table('global_params', schema=None) as batch_op:
        batch_op.drop_index('idx_global_params_class_name')

    op.drop_table('global_params')
    with op.batch_alter_table('file_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_attachments_file_id'))
        batch_op.drop_index('idx_file_attachments_entity')

    op.drop_table('file_attachments')
    op.drop_table('audit_logs')
    with op.batch_alter_table('ai_provider_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_provider_configs_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_provider_configs_provider_type'))
        batch_op.drop_index(batch_op.f('ix_ai_provider_configs_provider_name'))
        batch_op.drop_index('idx_ai_provider_user_type')
        batch_op.drop_index('idx_ai_provider_enabled_default')

    op.drop_table('ai_provider_configs')
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_conversations_conversation_id'))

    op.drop_table('ai_conversations')
    # ### end Alembic commands ###
