"""Add API test case models

Revision ID: ad3c4345ee46
Revises: 0fdf067e89d0
Create Date: 2026-01-30 20:49:04.270364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'ad3c4345ee46'
down_revision: Union[str, Sequence[str], None] = '0fdf067e89d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 创建 API 测试用例表
    op.create_table('apitestcase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('yaml_content', sa.String(), nullable=False),
    sa.Column('config_data', sqlite.JSON(), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=True),
    sa.Column('tags', sqlite.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['projectenvironment.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apitestcase', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_apitestcase_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_apitestcase_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_apitestcase_environment_id'), ['environment_id'], unique=False)

    # 创建 API 测试步骤表（可选）
    op.create_table('apiteststep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(), nullable=False),
    sa.Column('step_config', sqlite.JSON(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['apitestcase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apiteststep', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_apiteststep_test_case_id'), ['test_case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_apiteststep_step_order'), ['step_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_apiteststep_step_type'), ['step_type'], unique=False)

    # 创建 API 测试执行记录表
    op.create_table('apitestexecution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('result_data', sqlite.JSON(), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('passed_steps', sa.Integer(), nullable=False),
    sa.Column('failed_steps', sa.Integer(), nullable=False),
    sa.Column('skipped_steps', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('error_category', sa.String(), nullable=True),
    sa.Column('execution_options', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['projectenvironment.id'], ),
    sa.ForeignKeyConstraint(['test_case_id'], ['apitestcase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apitestexecution', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_apitestexecution_test_case_id'), ['test_case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_apitestexecution_environment_id'), ['environment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_apitestexecution_status'), ['status'], unique=False)

    # 创建 API 测试步骤结果表（可选）
    op.create_table('apiteststepresult',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('performance_metrics', sqlite.JSON(), nullable=False),
    sa.Column('response_data', sqlite.JSON(), nullable=False),
    sa.Column('validations', sqlite.JSON(), nullable=False),
    sa.Column('extracted_vars', sqlite.JSON(), nullable=False),
    sa.Column('error_info', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['apitestexecution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apiteststepresult', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_apiteststepresult_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_apiteststepresult_status'), ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apiteststepresult', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apiteststepresult_status'))
        batch_op.drop_index(batch_op.f('ix_apiteststepresult_execution_id'))

    op.drop_table('apiteststepresult')

    with op.batch_alter_table('apitestexecution', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apitestexecution_status'))
        batch_op.drop_index(batch_op.f('ix_apitestexecution_environment_id'))
        batch_op.drop_index(batch_op.f('ix_apitestexecution_test_case_id'))

    op.drop_table('apitestexecution')

    with op.batch_alter_table('apiteststep', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apiteststep_step_type'))
        batch_op.drop_index(batch_op.f('ix_apiteststep_step_order'))
        batch_op.drop_index(batch_op.f('ix_apiteststep_test_case_id'))

    op.drop_table('apiteststep')

    with op.batch_alter_table('apitestcase', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apitestcase_environment_id'))
        batch_op.drop_index(batch_op.f('ix_apitestcase_name'))
        batch_op.drop_index(batch_op.f('ix_apitestcase_project_id'))

    op.drop_table('apitestcase')
    # ### end Alembic commands ###
