"""Update scenario models - add priority, tags, variables, created_by

Revision ID: b9849f1b4fe4
Revises: 001_initial
Create Date: 2026-02-16 16:48:04.281291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9849f1b4fe4'
down_revision: Union[str, Sequence[str], None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('pre_sql', sa.Text(), nullable=True),
    sa.Column('post_sql', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenarios_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenarios_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('plan_scenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_plan_scenarios_plan_order'))
        batch_op.drop_index(batch_op.f('ix_plan_scenarios_scenario_id'))
        batch_op.drop_index(batch_op.f('ix_plan_scenarios_test_plan_id'))

    op.drop_table('plan_scenarios')
    with op.batch_alter_table('test_plan_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_plan_executions_status'))
        batch_op.drop_index(batch_op.f('ix_test_plan_executions_test_plan_id'))

    op.drop_table('test_plan_executions')
    with op.batch_alter_table('test_scenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_scenarios_project_id'))

    op.drop_table('test_scenarios')
    with op.batch_alter_table('env_variables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_env_variables_env_name_global'))
        batch_op.drop_index(batch_op.f('ix_env_variables_environment_id'))
        batch_op.drop_index(batch_op.f('ix_env_variables_is_global'))

    op.drop_table('env_variables')
    with op.batch_alter_table('plan_execution_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_execution_steps_status'))
        batch_op.drop_index(batch_op.f('ix_plan_execution_steps_test_plan_execution_id'))

    op.drop_table('plan_execution_steps')
    with op.batch_alter_table('test_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_plans_project_id'))
        batch_op.drop_index(batch_op.f('ix_test_plans_status'))

    op.drop_table('test_plans')
    with op.batch_alter_table('database_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_database_configs_project_variable'))
        batch_op.drop_index(batch_op.f('ix_database_configs_project_id'))

    op.drop_table('database_configs')
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('csv_data', sa.Text(), nullable=False))
        batch_op.alter_column('scenario_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_datasets_project_id'), ['project_id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'scenarios', ['scenario_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('data')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_created_by'), ['created_by'], unique=False)

    with op.batch_alter_table('scenario_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('keyword_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('keyword_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('parameters',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_scenario_steps_scenario_order'))
        batch_op.create_index('idx_scenario_steps_scenario_id', ['scenario_id'], unique=False)
        batch_op.create_index('idx_scenario_steps_sort_order', ['sort_order'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'scenarios', ['scenario_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('keyword_id')
        batch_op.drop_column('step_order')
        batch_op.drop_column('expected_result')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_users_email'))
        batch_op.drop_index(batch_op.f('idx_users_username'))
        batch_op.create_index('idx_users_oauth', ['oauth_provider', 'oauth_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index('idx_users_oauth')
        batch_op.create_index(batch_op.f('idx_users_username'), ['username'], unique=1)
        batch_op.create_index(batch_op.f('idx_users_email'), ['email'], unique=1)

    with op.batch_alter_table('scenario_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_result', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('step_order', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('keyword_id', sa.VARCHAR(length=36), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'test_scenarios', ['scenario_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'keywords', ['keyword_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index('idx_scenario_steps_sort_order')
        batch_op.drop_index('idx_scenario_steps_scenario_id')
        batch_op.create_index(batch_op.f('idx_scenario_steps_scenario_order'), ['scenario_id', 'step_order'], unique=1)
        batch_op.alter_column('parameters',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('sort_order')
        batch_op.drop_column('keyword_name')
        batch_op.drop_column('keyword_type')
        batch_op.drop_column('description')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_created_by'))

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'test_scenarios', ['scenario_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_datasets_project_id'))
        batch_op.alter_column('scenario_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('csv_data')
        batch_op.drop_column('project_id')

    op.create_table('database_configs',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('variable_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('db_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('host', sa.VARCHAR(length=255), nullable=False),
    sa.Column('port', sa.INTEGER(), nullable=False),
    sa.Column('initial_database', sa.VARCHAR(length=255), nullable=True),
    sa.Column('username', sa.VARCHAR(length=255), nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('connection_status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('last_tested_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('database_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_database_configs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_database_configs_project_variable'), ['project_id', 'variable_name'], unique=1)

    op.create_table('test_plans',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('cron_expression', sa.VARCHAR(length=255), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'active'"), nullable=False),
    sa.Column('next_run', sa.DATETIME(), nullable=True),
    sa.Column('last_run', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_plans_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_plans_project_id'), ['project_id'], unique=False)

    op.create_table('plan_execution_steps',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('test_plan_execution_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('scenario_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['test_plan_execution_id'], ['test_plan_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan_execution_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_execution_steps_test_plan_execution_id'), ['test_plan_execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_execution_steps_status'), ['status'], unique=False)

    op.create_table('env_variables',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('environment_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('value', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('is_global', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['project_environments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('env_variables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_env_variables_is_global'), ['is_global'], unique=False)
        batch_op.create_index(batch_op.f('ix_env_variables_environment_id'), ['environment_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_env_variables_env_name_global'), ['environment_id', 'name', 'is_global'], unique=1)

    op.create_table('test_scenarios',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('pre_sql', sa.TEXT(), nullable=True),
    sa.Column('post_sql', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_scenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_scenarios_project_id'), ['project_id'], unique=False)

    op.create_table('test_plan_executions',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('test_plan_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('total_scenarios', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('passed_scenarios', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('failed_scenarios', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('skipped_scenarios', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['test_plan_id'], ['test_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_plan_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_plan_executions_test_plan_id'), ['test_plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_plan_executions_status'), ['status'], unique=False)

    op.create_table('plan_scenarios',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('test_plan_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('scenario_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('execution_order', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['test_scenarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_plan_id'], ['test_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan_scenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_scenarios_test_plan_id'), ['test_plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_scenarios_scenario_id'), ['scenario_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_plan_scenarios_plan_order'), ['test_plan_id', 'execution_order'], unique=1)

    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenarios_project_id'))
        batch_op.drop_index(batch_op.f('ix_scenarios_created_by'))

    op.drop_table('scenarios')
    # ### end Alembic commands ###
